### ISSUE TITLE
Playstation 2 emulator request

### ISSUE THREAD

**Issue by google0101-ryan** [DerekTurtleRoe/awesome-emulators#13]
I’d like my emulator, [Emotional](https://github.com/google0101-ryan/Emotional) to be added to this list. It is in active development and already boots demos such as 3stars and ps2tuts.

Thanks for your consideration!

**Comment by DerekTurtleRoe** [comment]
@google0101-ryan I will add this, seems interesting! Good luck and hope the project goes well! 😄
