### ISSUE TITLE
Add DS Emulator

### ISSUE THREAD

**Issue by strayacode** [DerekTurtleRoe/awesome-emulators#17]
I would like to add my DS emulator [yuugen](https://github.com/strayacode/yuugen). It can boot quite a few games and has a recently added JIT with an ARM64 backend

**Comment by DerekTurtleRoe** [comment]
@strayacode I will add this to the list of emulators to add after the next major update! Thanks so much for the info! 😄 

Good luck with your emulator!

**Comment by strayacode** [comment]
Alright cool. I just added a license :)

**Comment by DerekTurtleRoe** [comment]
@strayacode Thanks so much! I will add it in the next update. 😄

**Comment by DerekTurtleRoe** [comment]
Added as of the latest commit, so I am going to close this. Thanks for letting me know about it! 😄
