### ISSUE TITLE
new emulators

### ISSUE THREAD

**Issue by amirh123123** [DerekTurtleRoe/awesome-emulators#31]
ChillyGB
https://github.com/AuroraViola/ChillyGB
droid arcadia
http://amigan.1emu.net/releases/
AmiArcadia 
http://amigan.1emu.net/releases/
and win arcadia
http://amigan.1emu.net/releases/
GameEx Multiplatform
https://forums.gameex.com/forums/files/file/2555-gameex-multiplatform/
GameEx/Arcade
https://forums.gameex.com/forums/
projectaracade
projectarcade.ru
https://github.com/PRO100BYTE/ProjectArcade
noods
https://github.com/Hydr8gon/NooDS

**Comment by DerekTurtleRoe** [comment]
Alright, they've all been added, thanks for the suggestions! 😄
